## Build stage
#FROM bellsoft/liberica-runtime-container:jdk-21-cds-musl AS build
#WORKDIR /builder
#COPY . .
#RUN ./gradlew clean build

# Optimization stage
FROM bellsoft/liberica-runtime-container:jdk-21-cds-musl  AS optimizer
WORKDIR /optimizer
#COPY --from=build /builder/build/libs/*.jar application.jar
COPY ./build/libs/*.jar application.jar
RUN java -Djarmode=tools -jar application.jar extract --layers --destination extracted

# Final image
FROM bellsoft/liberica-runtime-container:jdk-21-cds-musl
WORKDIR /application
COPY --from=optimizer /optimizer/extracted/dependencies/ ./
COPY --from=optimizer /optimizer/extracted/spring-boot-loader/ ./
COPY --from=optimizer /optimizer/extracted/snapshot-dependencies/ ./
COPY --from=optimizer /optimizer/extracted/application/ ./
# there is an issue regarding aot + cds when migration with flyway is used: https://github.com/spring-projects/spring-boot/issues/41348
# solution is to not use aot during the cds run. Apparently the cds archive will contain the aot generated classes anyway instead of the spring autoconfigure classes
RUN java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar application.jar --spring.profiles.active=cds
ENTRYPOINT ["java","-Dspring.aot.enabled=true","-XX:SharedArchiveFile=application.jsa","-Xshare:on","-XX:+UseParallelGC","-XX:MaxRAMPercentage=75","-XX:MinRAMPercentage=75","-jar","application.jar"]
