apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-app
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-app
    spec:
      containers:
      - image: ghcr.io/philipphe98/bachelor-thesis/micronaut-aot-native:main
        name: micronaut-aot-native
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75"
        - name: JDBC_URL
          value: jdbc:postgresql://mypostgresph.postgres.database.azure.com:5432/postgres?sslmode=require
        - name: JDBC_USER
          value: azureuser
        - name: JDBC_PASSWORD
          value: "#iM&rx]Fj3]Ah!g"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
