FROM ghcr.io/graalvm/graalvm-community:21 AS builder
WORKDIR /builder
COPY . .
RUN ./gradlew nativeOptimizedCompile

FROM bellsoft/alpaquita-linux-base:glibc
WORKDIR /application
COPY --from=builder /builder/build/native/nativeOptimizedCompile/micronaut-aot micronaut-aot
ENTRYPOINT ["./micronaut-aot"]
