services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    image: crac-image-restore:1.0
    ports:
      - "8080:8080"
    cap_add:
      - CHECKPOINT_RESTORE
      - SYS_PTRACE
    restart: no
#    build:
#      context: .
#      dockerfile: Dockerfile-cds

    depends_on:
      - db